
title: RatVM
description: RatVM compiler and console interpreter
github_username: grendrake
# you can comment the below line out if your repo name is not different than your baseurl
github_repo: "ratvm"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

theme: jekyll-theme-midnight
